cypher/urls.py
from django.urls import path
from . import views

app_name = 'cypher'
urlpatterns = [
    path('', views.cypher_main,  name="cypher-main"),
    path('affine-cipher/', views.affine, name='affine'),
    path('caesar-cipher/', views.caesar, name='caesar'),
    path('atbash-cipher/', views.atbash, name='atbash'),
    path('bacon-cipher/', views.bacon, name='bacon'),
    path('polybius-cipher/', views.polybius, name='polybius'),
    path('rot13-cipher/', views.rot13, name='rot13'),
]

home/urls.py
from django.conf.urls import url
from django.urls import path, include
from django.views.generic import TemplateView

from . import views

urlpatterns = [
    path('', views.main_page, name="main_page"),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),

    path('home/', TemplateView.as_view(template_name='home/home/main.html'), name='home_page'),
    path('home/concentus', TemplateView.as_view(template_name='home/concentus/index.html'), name='concentus'),
    path('home/constellation', TemplateView.as_view(template_name='home/constellation/index.html'), name='constellation'),
    path('home/expressionism', TemplateView.as_view(template_name='home/expressionism/index.html'), name='expressionism'),
    path('home/expressionism2', TemplateView.as_view(template_name='home/expressionism2/index.html'), name='expressionism2'),
    path('home/fractal', TemplateView.as_view(template_name='home/fractal/index.html'), name='fractal'),
    path('home/galaxy', TemplateView.as_view(template_name='home/galaxy/index.html'), name='galaxy'),
    path('home/heartverse', TemplateView.as_view(template_name='home/heartverse/index.html'), name='heartverse'),
    path('home/infinity', TemplateView.as_view(template_name='home/infinity/index.html'), name='infinity'),
    path('home/neon', TemplateView.as_view(template_name='home/neon/index.html'), name='neon'),
    path('home/phoenix', TemplateView.as_view(template_name='home/phoenix/index.html'), name='phoenix'),
    path('home/psychedelic', TemplateView.as_view(template_name='home/psychedelic/index.html'), name='psychedelic'),
    path('home/spirals', TemplateView.as_view(template_name='home/spirals/index.html'), name='spirals'),
    path('home/whirlpool', TemplateView.as_view(template_name='home/whirlpool/index.html'), name='whirlpool'),
    path('home/secret', views.secret, name='secret'),

    path('home/xmas-tree', TemplateView.as_view(template_name='home/xmas-tree/index.html'), name='xmas-home'),
    path('home/xmas-tree/intro', TemplateView.as_view(template_name='home/xmas-tree/intro.html'), name='xmas-intro'),
    path('home/xmas-tree/xmas-scene', TemplateView.as_view(template_name='home/xmas-tree/xmas-scene/index.html'), name='xmas-scene'),
    path('home/xmas-tree/xmas-special', TemplateView.as_view(template_name='home/xmas-tree/xmas-special/index.html'), name='xmas-special'),
    path('home/xmas-tree/xmas-game', TemplateView.as_view(template_name='home/xmas-tree/xmas-game/index.html'), name='xmas-game'),
    path('home/xmas-tree/xmas-calendar', TemplateView.as_view(template_name='home/xmas-tree/xmas-calendar/index.html'), name='xmas-calendar'),
]

jackshen/urls.py
import os

from django.conf.urls.static import static
from django.contrib import admin
from django.views.static import serve
from django.urls import path, include

from jackshen import settings
from jackshen.settings import BASE_DIR

urlpatterns = [
    path('', include("home.urls")),
    path('admin/', admin.site.urls),
    path('todo/', include('todo.urls', namespace='todo')),
    path('cypher/', include('cypher.urls', namespace='cypher')),
    path('ip-locator/', include('ip_locator.urls', namespace='ip_locator')),
    path('movie-finder/', include('movie_finder.urls', namespace='movie-finder')),
]

handler403 = 'home.views.error_403'
handler404 = 'home.views.error_404'
handler500 = 'home.views.error_500'

# Serve the favicon
urlpatterns += [
    path('favicon.ico', serve, {
        'path': 'favicon.ico',
        'document_root': os.path.join(BASE_DIR, 'home/static'),
    }),
]

# Serve the media
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cypher/models.py
from django.db import models

# Create your models here.

cypher/views.py
from django.shortcuts import render
from .utils.monoalphabetic.atbash import solve_atbash
from .utils.monoalphabetic.bacon import encrypt_bacon, decrypt_bacon
from .utils.monoalphabetic.caesar import encrypt_caesar, decrypt_caesar
from .utils.monoalphabetic.polybius import encrypt_polybius, decrypt_polybius
from .utils.monoalphabetic.affine import encrypt_affine, decrypt_affine


def cypher_main(request):
    return render(request, 'cypher/main.html')


def caesar(request):
    if request.method == 'POST':
        caesarList = False
        decrypt = False

        if request.POST['cipherEncrypt'] == 'False':
            decrypt = True
            ciphertext = request.POST['ciphertext']
            shift = request.POST.get('shift', False)

            if shift:
                shift = int(shift)
                plaintext = decrypt_caesar(ciphertext, shift=shift)
            else:
                caesarList = True
                plaintext = decrypt_caesar(ciphertext)
        else:
            plaintext = request.POST['plaintext']
            shift = int(request.POST['shift'])
            ciphertext = encrypt_caesar(plaintext, shift)

        return render(request, 'cypher/caesar.html', {'plaintext': plaintext, 'shift': shift,
                                                      'ciphertext': ciphertext, 'caesarList': caesarList,
                                                      'decrypt': decrypt})

    return render(request, 'cypher/caesar.html')


def atbash(request):
    if request.method == 'POST':
        decrypt = False

        if request.POST['cipherEncrypt'] == 'False':
            decrypt = True

            ciphertext = request.POST['ciphertext']
            plaintext = solve_atbash(ciphertext)
        else:
            plaintext = request.POST['plaintext']
            ciphertext = solve_atbash(plaintext)

        return render(request, 'cypher/atbash.html', {'plaintext': plaintext, 'ciphertext': ciphertext,
                                                      'decrypt': decrypt})

    return render(request, 'cypher/atbash.html')


def rot13(request):
    if request.method == 'POST':
        decrypt = False

        if request.POST['cipherEncrypt'] == 'False':
            decrypt = True

            ciphertext = request.POST['ciphertext']
            plaintext = decrypt_caesar(ciphertext, shift=13)
        else:
            plaintext = request.POST['plaintext']
            ciphertext = encrypt_caesar(plaintext, shift=13)

        return render(request, 'cypher/rot13.html', {'plaintext': plaintext, 'ciphertext': ciphertext,
                                                     'decrypt': decrypt})

    return render(request, 'cypher/rot13.html')


def bacon(request):
    if request.method == 'POST':
        decrypt = False
        origin_table = request.POST.get('originalTable', False)

        if request.POST['cipherEncrypt'] == 'False':
            decrypt = True
            ciphertext = request.POST['ciphertext']

            if origin_table:
                plaintext = decrypt_bacon(ciphertext)
            else:
                plaintext = decrypt_bacon(ciphertext, original=False)
        else:
            plaintext = request.POST['plaintext']

            if origin_table:
                ciphertext = encrypt_bacon(plaintext)
            else:
                ciphertext = encrypt_bacon(plaintext, original=False)

        return render(request, 'cypher/bacon.html', {'plaintext': plaintext, 'ciphertext': ciphertext,
                                                     'decrypt': decrypt, 'originTable': origin_table})

    return render(request, 'cypher/bacon.html')


def polybius(request):
    if request.method == 'POST':
        decrypt = False
        encryption_key = request.POST['encryptionKey']

        if request.POST['cipherEncrypt'] == 'False':
            decrypt = True
            ciphertext = request.POST['ciphertext']
            plaintext = decrypt_polybius(ciphertext, encryption_key)
        else:
            plaintext = request.POST['plaintext']
            ciphertext = encrypt_polybius(plaintext, encryption_key)

        return render(request, 'cypher/polybius.html', {'plaintext': plaintext, 'ciphertext': ciphertext,
                                                        'decrypt': decrypt, 'encryption_key': encryption_key})

    return render(request, 'cypher/polybius.html')


def affine(request):
    if request.method == 'POST':
        decrypt = False
        coefs = (int(request.POST['acoef']), int(request.POST['bcoef']))

        if request.POST['cipherEncrypt'] == 'False':
            decrypt = True
            ciphertext = request.POST['ciphertext']
            plaintext = decrypt_affine(ciphertext, coefs)
        else:
            plaintext = request.POST['plaintext']
            ciphertext = encrypt_affine(plaintext, coefs)

        return render(request, 'cypher/affine.html', {'plaintext': plaintext, 'ciphertext': ciphertext,
                                                      'decrypt': decrypt, 'acoef': coefs[0], 'bcoef': coefs[1]})

    return render(request, 'cypher/affine.html')

templates/cypher/affine.html
{% extends 'cypher/base.html' %}
{% load static %}
{% block title %}Affine Cipher{% endblock %}

{% block extrahead %}
<link rel="stylesheet" href="{% static 'libs/css/icons.css' %}">
{% endblock %}

{% block content %}
<form id="cipherDecrypt" class="cipher-form" action="{% url "cypher:affine" %}" method="POST" autocomplete="off">
    {% csrf_token %}
    <input type="hidden" value="False" name="cipherEncrypt">
    <div class="container">
        <header class="cipher-form-header">
            <h2 class="title">Affine Decoder</h2>
        </header>

        <div class="cipher-form-main">
            <section class="form-content">
                <div class="row-wrapper">
                    <div class="element decrypt">
                        <label for="ciphertext">Ciphertext</label>
                        <textarea id="ciphertext" name="ciphertext" minlength="5" maxlength="1000" required>{% if ciphertext and decrypt %}{{ ciphertext }}{% else %}Dwwdfn wrpruurz dw 6:45 iurp wkh qruwk, wkh pdlq wdujhw - wkh vrxwkhuq jdwh.{% endif %}</textarea>
                    </div>
                    <div class="element abcoef">
                        <label for="acoef">A COEFFICIENT</label>
                        <input type="number" id="acoef" name="acoef" min="0" max="25" value="{% if ciphertext and decrypt %}{{ acoef }}{% else %}1{% endif %}" required>
                    </div>
                     <div class="element abcoef">
                        <label for="bcoef">B COEFFICIENT</label>
                        <input type="number" id="bcoef" name="bcoef" min="0" max="25" value="{% if ciphertext and decrypt %}{{ bcoef }}{% else %}3{% endif %}" required>
                    </div>
                </div>

                {% if plaintext and decrypt %}
                <div class="row-wrapper">
                    <div class="element encrypt">
                        <label for="plaintext">Plaintext</label>
                        <textarea id="plaintext" readonly="readonly">{{ plaintext }}</textarea>
                    </div>
                </div>
                {% endif %}
            </section>
        </div>

        <footer class="form-footer">
            <div class="footer-wrapper">
                <input type="submit" value="Decrypt!">
            </div>
        </footer>
    </div>
</form>

<form id="cipherEncrypt" class="cipher-form" action="{% url "cypher:affine" %}" method="POST" autocomplete="off">
    {% csrf_token %}
    <input type="hidden" value="True" name="cipherEncrypt">
    <div class="container">
        <header class="cipher-form-header">
            <h2 class="title">Affine Encoder</h2>
        </header>

        <div class="cipher-form-main">
            <section class="form-content">
                <div class="row-wrapper">
                    <div class="element encrypt">
                        <label for="plaintext">Plaintext</label>
                        <textarea id="plaintext" name="plaintext" minlength="5" maxlength="1000" required>{% if plaintext and not decrypt %}{{ plaintext }}{% else %}Attack tomorrow at 6:45 from the north, the main target - the southern gate.{% endif %}</textarea>
                    </div>
                    <div class="element abcoef">
                        <label for="acoef">A COEFF</label>
                        <input type="number" id="acoef" name="acoef" min="0" max="25" value="{% if ciphertext and not decrypt %}{{ acoef }}{% else %}1{% endif %}" required>
                    </div>
                     <div class="element abcoef">
                        <label for="bcoef">B COEFF</label>
                        <input type="number" id="bcoef" name="bcoef" min="0" max="25" value="{% if ciphertext and not decrypt %}{{ bcoef }}{% else %}3{% endif %}" required>
                    </div>
                </div>

                {% if ciphertext and not decrypt %}
                <div class="row-wrapper">
                    <div class="element encrypt">
                        <label for="ciphertext">Ciphertext</label>
                        <textarea id="ciphertext" readonly="readonly">{{ ciphertext }}</textarea>
                    </div>
                </div>
                {% endif %}
            </section>
        </div>

        <footer class="form-footer">
            <div class="footer-wrapper">
                <input type="submit" value="Encrypt!">
            </div>
        </footer>
    </div>
</form>
{% endblock %}

{% block extra_js %}
<script src="{% static 'cypher/js/cypher.js' %}"></script>
<script>
{% if decrypt %}
decrypt();
{% endif %}
</script>
{% endblock extra_js %}

templates/cypher/atbash.html
{% extends 'cypher/base.html' %}
{% load static %}
{% block title %}Atbash Cipher{% endblock %}

{% block extrahead %}
<link rel="stylesheet" href="{% static 'libs/css/icons.css' %}">
{% endblock %}

{% block content %}
<form id="cipherDecrypt" class="cipher-form" action="{% url "cypher:atbash" %}" method="POST" autocomplete="off">
    {% csrf_token %}
    <input type="hidden" value="False" name="cipherEncrypt">
    <div class="container">
        <header class="cipher-form-header">
            <h2 class="title">Atbash Decoder</h2>
        </header>

        <div class="cipher-form-main">
            <section class="form-content">
                <div class="row-wrapper">
                    <div class="element decrypt">
                        <label for="ciphertext">Ciphertext</label>
                        <textarea id="ciphertext" name="ciphertext" minlength="5" maxlength="1000" required>{% if ciphertext and decrypt %}{{ ciphertext }}{% else %}Zggzxp glnliild zg 4:65 uiln gsv mligs, gsv nzrm gzitvg - gsv hlfgsvim tzgv.{% endif %}</textarea>
                    </div>
                </div>

                {% if plaintext and decrypt %}
                <div class="row-wrapper">
                    <div class="element encrypt">
                        <label for="plaintext">Plaintext</label>
                        <textarea id="plaintext" readonly="readonly">{{ plaintext }}</textarea>
                    </div>
                </div>
                {% endif %}
            </section>
        </div>

        <footer class="form-footer">
            <div class="footer-wrapper">
                <input type="submit" value="Decrypt!">
            </div>
        </footer>
    </div>
</form>

<form id="cipherEncrypt" class="cipher-form" action="{% url "cypher:atbash" %}" method="POST" autocomplete="off">
    {% csrf_token %}
    <input type="hidden" value="True" name="cipherEncrypt">
    <div class="container">
        <header class="cipher-form-header">
            <h2 class="title">Atbash Encoder</h2>
        </header>

        <div class="cipher-form-main">
            <section class="form-content">
                <div class="row-wrapper">
                    <div class="element encrypt">
                        <label for="plaintext">Plaintext</label>
                        <textarea id="plaintext" name="plaintext" minlength="5" maxlength="1000" required>{% if plaintext and not decrypt %}{{ plaintext }}{% else %}Attack tomorrow at 6:45 from the north, the main target - the southern gate.{% endif %}</textarea>
                    </div>
                </div>

                {% if ciphertext and not decrypt %}
                <div class="row-wrapper">
                    <div class="element encrypt">
                        <label for="ciphertext">Ciphertext</label>
                        <textarea id="ciphertext" readonly="readonly">{{ ciphertext }}</textarea>
                    </div>
                </div>
                {% endif %}
            </section>
        </div>

        <footer class="form-footer">
            <div class="footer-wrapper">
                <input type="submit" value="Encrypt!">
            </div>
        </footer>
    </div>
</form>
{% endblock %}

{% block extra_js %}
<script src="{% static 'cypher/js/cypher.js' %}"></script>
<script>
{% if decrypt %}
decrypt();
{% endif %}
</script>
{% endblock extra_js %}

templates/cypher/bacon.html
{% extends 'cypher/base.html' %}
{% load static %}
{% block title %}Bacon Cipher{% endblock %}

{% block extrahead %}
<link rel="stylesheet" href="{% static 'libs/css/icons.css' %}">
{% endblock %}

{% block content %}
<form id="cipherDecrypt" class="cipher-form" action="{% url "cypher:bacon" %}" method="POST" autocomplete="off">
    {% csrf_token %}
    <input type="hidden" value="False" name="cipherEncrypt">
    <div class="container">
        <header class="cipher-form-header">
            <h2 class="title">Bacon Decoder</h2>
        </header>

        <div class="cipher-form-main">
            <section class="form-content">
                <div class="row-wrapper">
                    <div class="element decrypt">
                        <label for="ciphertext">Ciphertext</label>
                        <textarea id="ciphertext" name="ciphertext" minlength="5" maxlength="1000" required>{% if ciphertext and decrypt %}{{ ciphertext }}{% else %}AAAAABAABABAABAAAAAAAAABAABAABBAABAABBABABABBABBABBAAAABAAAAABBABBABAAAABABBAAAAABBABABABBBAABAAABBBAABAAABBAAABBABBAAAABAABAAABBB{% endif %}</textarea>
                    </div>

                    <div class="element original-table">
                        <label style="display: block; text-align: center;">Use Original Table (i=j, u=v)</label>
                        <label for="originalDecode" class="check" style="text-align: center; padding-right: 0; display: block;">
                            <input type="checkbox" value="True" name="originalTable" id="originalDecode" class="hidden" {% if originTable and decrypt %}checked{% endif %}/>
                            <span class="label" style="margin-right: 0;"></span>
                        </label>
                    </div>
                </div>

                {% if plaintext and decrypt %}
                <div class="row-wrapper">
                    <div class="element encrypt">
                        <label for="plaintext">Plaintext</label>
                        <textarea id="plaintext" readonly="readonly">{{ plaintext }}</textarea>
                    </div>
                </div>
                {% endif %}
            </section>
        </div>

        <footer class="form-footer">
            <div class="footer-wrapper">
                <input type="submit" value="Decrypt!">
            </div>
        </footer>
    </div>
</form>

<form id="cipherEncrypt" class="cipher-form" action="{% url "cypher:bacon" %}" method="POST" autocomplete="off">
    {% csrf_token %}
    <input type="hidden" value="True" name="cipherEncrypt">
    <div class="container">
        <header class="cipher-form-header">
            <h2 class="title">Bacon Encoder</h2>
        </header>

        <div class="cipher-form-main">
            <section class="form-content">
                <div class="row-wrapper">
                    <div class="element encrypt">
                        <label for="plaintext">Plaintext</label>
                        <textarea id="plaintext" name="plaintext" minlength="5" maxlength="1000" required>{% if plaintext and not decrypt %}{{ plaintext }}{% else %}Attack tomorrow from the north.{% endif %}</textarea>
                    </div>

                    <div class="element original-table">
                        <label style="display: block; text-align: center;">Use Original Table (i=j, u=v)</label>
                        <label for="originalEncode" class="check" style="text-align: center; padding-right: 0; display: block;">
                            <input type="checkbox" value="True" name="originalTable" id="originalEncode" class="hidden" {% if originTable and not decrypt %}checked{% endif %}/>
                            <span class="label" style="margin-right: 0;"></span>
                        </label>
                    </div>
                </div>

                {% if ciphertext and not decrypt %}
                <div class="row-wrapper">
                    <div class="element encrypt">
                        <label for="ciphertext">Ciphertext</label>
                        <textarea id="ciphertext" readonly="readonly">{{ ciphertext }}</textarea>
                    </div>
                </div>
                {% endif %}
            </section>
        </div>

        <footer class="form-footer">
            <div class="footer-wrapper">
                <input type="submit" value="Encrypt!">
            </div>
        </footer>
    </div>
</form>
{% endblock %}

{% block extra_js %}
<script src="{% static 'cypher/js/cypher.js' %}"></script>
<script>
{% if decrypt %}
decrypt();
{% endif %}
</script>
{% endblock extra_js %}

templates/cypher/main.html
{% extends 'cypher/base.html' %}
{% load static %}

{% block extrahead %}
<link rel="stylesheet" href="{% static 'home/home/css/home.css' %}">
<style>
#Switcher {
    display: none;
}
</style>
{% endblock %}

{% block content %}
<h1 class="section-title">Monoalphabetic Substitution Ciphers</h1>

<div class='items'>
    <div class='item'>
        <svg class='item-svg' preserveAspectRatio='xMidYMid slice' viewBox='0 0 300 200'>
            <a href="{% url "cypher:atbash" %}" target="_self">
                <defs>
                    <clipPath id='clip-0'>
                        <circle cx='0' cy='0' fill='#000' r='150px'></circle>
                    </clipPath>
                </defs>
                <text class='svg-text' dy='.3em' x='50%' y='50%'>
                    Atbash Cipher
                </text>
                <g clip-path='url(#clip-0)'>
                    <image class="item-image" height='100%' preserveAspectRatio='xMinYMin slice' width='100%' xlink:href='{% static 'img/item-back.webp' %}'></image>
                    <text class='svg-masked-text' dy='.3em' x='50%' y='50%'>
                        Atbash Cipher
                    </text>
                </g>
            </a>
        </svg>
    </div>

    <div class='item'>
        <svg class='item-svg' preserveAspectRatio='xMidYMid slice' viewBox='0 0 300 200'>
            <a href="{% url "cypher:rot13" %}" target="_self">
                <defs>
                    <clipPath id='clip-1'>
                        <circle cx='0' cy='0' fill='#000' r='150px'></circle>
                    </clipPath>
                </defs>
                <text class='svg-text' dy='.3em' x='50%' y='50%'>
                    ROT13 Cipher
                </text>
                <g clip-path='url(#clip-1)'>
                    <image class="item-image" height='100%' preserveAspectRatio='xMinYMin slice' width='100%' xlink:href='{% static 'img/item-back.webp' %}'></image>
                    <text class='svg-masked-text' dy='.3em' x='50%' y='50%'>
                        ROT13 Cipher
                    </text>
                </g>
            </a>
        </svg>
    </div>

    <div class='item'>
        <svg class='item-svg' preserveAspectRatio='xMidYMid slice' viewBox='0 0 300 200'>
            <a href="{% url "cypher:caesar" %}" target="_self">
                <defs>
                    <clipPath id='clip-2'>
                        <circle cx='0' cy='0' fill='#000' r='150px'></circle>
                    </clipPath>
                </defs>
                <text class='svg-text' dy='.3em' x='50%' y='50%'>
                    Caesar Cipher
                </text>
                <g clip-path='url(#clip-2)'>
                    <image class="item-image" height='100%' preserveAspectRatio='xMinYMin slice' width='100%' xlink:href='{% static 'img/item-back.webp' %}'></image>
                    <text class='svg-masked-text' dy='.3em' x='50%' y='50%'>
                        Caesar Cipher
                    </text>
                </g>
            </a>
        </svg>
    </div>



    <div class='item'>
        <svg class='item-svg' preserveAspectRatio='xMidYMid slice' viewBox='0 0 300 200'>
            <a href="{% url "cypher:bacon" %}" target="_self">
                <defs>
                    <clipPath id='clip-3'>
                        <circle cx='0' cy='0' fill='#000' r='150px'></circle>
                    </clipPath>
                </defs>
                <text class='svg-text' dy='.3em' x='50%' y='50%'>
                    Baconian Cipher
                </text>
                <g clip-path='url(#clip-3)'>
                    <image class="item-image" height='100%' preserveAspectRatio='xMinYMin slice' width='100%' xlink:href='{% static 'img/item-back.webp' %}'></image>
                    <text class='svg-masked-text' dy='.3em' x='50%' y='50%'>
                        Baconian Cipher
                    </text>
                </g>
            </a>
        </svg>
    </div>

    <div class='item'>
        <svg class='item-svg' preserveAspectRatio='xMidYMid slice' viewBox='0 0 300 200'>
            <a href="{% url "cypher:polybius" %}" target="_self">
                <defs>
                    <clipPath id='clip-4'>
                        <circle cx='0' cy='0' fill='#000' r='150px'></circle>
                    </clipPath>
                </defs>
                <text class='svg-text' dy='.3em' x='50%' y='50%'>
                    Polybius Square
                </text>
                <g clip-path='url(#clip-4)'>
                    <image class="item-image" height='100%' preserveAspectRatio='xMinYMin slice' width='100%' xlink:href='{% static 'img/item-back.webp' %}'></image>
                    <text class='svg-masked-text' dy='.3em' x='50%' y='50%'>
                        Polybius Square
                    </text>
                </g>
            </a>
        </svg>
    </div>

    <div class='item'>
        <svg class='item-svg' preserveAspectRatio='xMidYMid slice' viewBox='0 0 300 200'>
            <a href="{% url "cypher:affine" %}" target="_self">
                <defs>
                    <clipPath id='clip-5'>
                        <circle cx='0' cy='0' fill='#000' r='150px'></circle>
                    </clipPath>
                </defs>
                <text class='svg-text' dy='.3em' x='50%' y='50%'>
                    Affine Cipher
                </text>
                <g clip-path='url(#clip-5)'>
                    <image class="item-image" height='100%' preserveAspectRatio='xMinYMin slice' width='100%' xlink:href='{% static 'img/item-back.webp' %}'></image>
                    <text class='svg-masked-text' dy='.3em' x='50%' y='50%'>
                        Affine Cipher
                    </text>
                </g>
            </a>
        </svg>
    </div>
</div>
{% endblock %}

{% block extra_js %}
<script src="{% static 'home/home/js/main_script.js' %}"></script>
{% endblock extra_js %}

templates/cypher/rot13.html
{% extends 'cypher/base.html' %}
{% load static %}
{% block title %}ROT13 Cipher{% endblock %}

{% block extrahead %}
<link rel="stylesheet" href="{% static 'libs/css/icons.css' %}">
{% endblock %}

{% block content %}
<form id="cipherDecrypt" class="cipher-form" action="{% url "cypher:rot13" %}" method="POST" autocomplete="off">
    {% csrf_token %}
    <input type="hidden" value="False" name="cipherEncrypt">
    <div class="container">
        <header class="cipher-form-header">
            <h2 class="title">ROT13 Decoder</h2>
        </header>

        <div class="cipher-form-main">
            <section class="form-content">
                <div class="row-wrapper">
                    <div class="element decrypt">
                        <label for="ciphertext">Ciphertext</label>
                        <textarea id="ciphertext" name="ciphertext" minlength="5" maxlength="1000" required>{% if ciphertext and decrypt %}{{ ciphertext }}{% else %}Nggnpx gbzbeebj ng 9:78 sebz gur abegu, gur znva gnetrg - gur fbhgurea tngr.{% endif %}</textarea>
                    </div>
                </div>

                {% if plaintext and decrypt %}
                <div class="row-wrapper">
                    <div class="element encrypt">
                        <label for="plaintext">Plaintext</label>
                        <textarea id="plaintext" readonly="readonly">{{ plaintext }}</textarea>
                    </div>
                </div>
                {% endif %}
            </section>
        </div>

        <footer class="form-footer">
            <div class="footer-wrapper">
                <input type="submit" value="Decrypt!">
            </div>
        </footer>
    </div>
</form>

<form id="cipherEncrypt" class="cipher-form" action="{% url "cypher:rot13" %}" method="POST" autocomplete="off">
    {% csrf_token %}
    <input type="hidden" value="True" name="cipherEncrypt">
    <div class="container">
        <header class="cipher-form-header">
            <h2 class="title">ROT13 Encoder</h2>
        </header>

        <div class="cipher-form-main">
            <section class="form-content">
                <div class="row-wrapper">
                    <div class="element encrypt">
                        <label for="plaintext">Plaintext</label>
                        <textarea id="plaintext" name="plaintext" minlength="5" maxlength="1000" required>{% if plaintext and not decrypt %}{{ plaintext }}{% else %}Attack tomorrow at 6:45 from the north, the main target - the southern gate.{% endif %}</textarea>
                    </div>
                </div>

                {% if ciphertext and not decrypt %}
                <div class="row-wrapper">
                    <div class="element encrypt">
                        <label for="ciphertext">Ciphertext</label>
                        <textarea id="ciphertext" readonly="readonly">{{ ciphertext }}</textarea>
                    </div>
                </div>
                {% endif %}
            </section>
        </div>

        <footer class="form-footer">
            <div class="footer-wrapper">
                <input type="submit" value="Encrypt!">
            </div>
        </footer>
    </div>
</form>
{% endblock %}

{% block extra_js %}
<script src="{% static 'cypher/js/cypher.js' %}"></script>
<script>
{% if decrypt %}
decrypt();
{% endif %}
</script>
{% endblock extra_js %}